project:
  type: website
  output-dir: docs

website:
  site-url: https://tesfayesalarin.github.io/YES-Seminars/
  title: "Seminar Group"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: events.qmd
        text: Events
      - href : people.qmd
        text: People
      #- href: contact.qmd
      #  text: Contact
  page-footer: "Â© 2025 Seminar Group | Built with Quarto & R"

format:
  html:
    date-title: "Presented on"
    theme: sandstone 
    css: styles.css
    toc: true
